config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  devise_for :users
  as :user do 
  	get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  	put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :bicycles
  root to: 'bicycles#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
	belongs_to :user
  has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :bicycle

  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bicycles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]
  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles = Bicycle.page(params[:page])
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)
    @bicycle.user_id = current_user.id
    respond_to do |format|
      if @bicycle.save
        if params[:images]
           params[:images].each { |image|
            @bicycle.pictures.create(image: image)
          }
        end
      

        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.require(:bicycle).permit(:name, :value, :description,:user_id,:pictures)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bicycles/_form.html.erb
<%= form_for @bicycle, :html => { multipart: true } do |form| %>
  <% if bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

      <ul>
      <% bicycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bicycle_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :bicycle_value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :bicycle_description %>
  </div>

  <ul>
    <li>ファイル１：<%= file_field_tag "images[]", type: :file %></li>
    <li>ファイル２：<%= file_field_tag "images[]", type: :file %></li>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bicycles/edit.html.erb
<h1>Editing Bicycle</h1>

<% breadcrumb :edit_bicycle %>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Show', @bicycle %> |
<%= link_to 'Back', bicycles_path %>

app/views/bicycles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>自転車屋さん</h1>
<% breadcrumb :bicycles %>
<%= page_entries_info @bicycles %>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>価格</th>
      <th>説明</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.name %></td>
        <td><%= bicycle.value %></td>
        <td><%= bicycle.description %></td>
        <td><%= link_to '詳細ページ', bicycle %></td>
        <td><%= link_to '編集', edit_bicycle_path(bicycle) %></td>
        <td><%= link_to '削除', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '出品ページ', new_bicycle_path %>

<%= paginate @bicycles %>

app/views/bicycles/new.html.erb
<h1>New Bicycle</h1>
<% breadcrumb :new_bicycle %>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Back', bicycles_path %>

app/views/bicycles/show.html.erb
<p id="notice"><%= notice %></p>
<% breadcrumb :show_bicycle, @bicycle %>

<p>
  <strong>Name:</strong>
  <%= @bicycle.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @bicycle.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bicycle.description %>
</p>
  <% @bicycle.pictures.each do |pic| %>
      <%= image_tag pic.image.url %>
  <% end %>

<%= link_to 'Edit', edit_bicycle_path(@bicycle) %> |
<%= link_to 'Back', bicycles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FifthEC2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if user_signed_in? %>
      Logged in as <%= current_user.email %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </head>

  <body>
  <header>
     <%= link_to 'トップ', root_path %>｜
            <% if user_signed_in? %> 
              
              Logged in as <%= current_user.email %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>｜
              <%= link_to "ポスト一覧", bicycles_path %>｜
              <%= link_to 'マイページ', user_path(current_user) %>
            <% else %>
              <%= link_to "ログイン", new_user_session_path %>
            <% end %>
    
  </header>
  <div class="container">
  <p>
  	<%= breadcrumbs separator: " &rsaquo; " %>
  </p>
  	
  </div>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<ul>  
      <li>  
        <%= link_to user_path(@user) do %>
          <div class="text">投稿数</div>  
          <div class="num"><%= @user.bicycles.count %></div>  
        <% end %>  
      </li>  
  </ul>



<% @user.bicycles.each do |bicycle| %>
      
      <div class="bicycle-name">
          <%= link_to bicycle.name %>
      </div>

  <% end %>